### ISSUE TITLE
No folders named like the README instructions?

### ISSUE THREAD

**Issue by hnlkaitan** [TheLastGimbus/GooglePhotosTakeoutHelper#30]
Hi, thought I'd give this a shot, however I noticed that after using takeout, I don't have any folders in the YYYY-MM-DD format or anything like that. Each takeout folder is mostly comprised of albums, with the closest being Photos from YYYY. I'm not sure if this is because it originally synced with Google Drive, or what.

And also, might be unrelated, but if using macOS, can I just copy-merge the folders so I have `./Takeout/Google\ Photos/<everything copy-merged here>` or should it each Takeout folder just be put into a folder (no merge) like `./folder/<Takeout [1-N]>`

**Comment by TheLastGimbus** [comment]
> or should it each Takeout folder just be put into a folder

Hm, you can probably do any of this, it should work anyway

Can you describe how you used your phots? Did you just use the app, or did you upload them by hand from some other camera, or what?

Also, `ls` of the folders would be nice, just put it in the code block please

**Comment by JoLander** [comment]
Hi,
I just stumbled over this tool and want to try as well. 
After running a takeout of all photos from Google I found the same strange folder structure. 
It seems that all photos are ordered in folders called 'Photos from YYYY' for every calender year. 
In addition, I have an extra folder for each album I created. These folders seems to have copies of the pictures already present in the 'Photos from YYYY' folders.
There are no folders at all named by a specific date.

**Comment by TheLastGimbus** [comment]
Jezus fucking Christ, Google...

**Comment by hnlkaitan** [comment]
Actually, now that you mention it, I believe that some time in the past, I _did_ upload my entire photo library to Google Photos library (some time between 2016-2018, since I thought it'd be nice to have my entire library in the cloud). So everything before that time was uploaded probably through the website or Google Drive (I don't remember at this point, honestly), and then almost everything after that was through the Google Photos app.

Directory tree that I have:
```
/Volumes
  |--San Disk Extreme
      |--Takeout
          |--Takeout 1
          |--Takeout 2
          |--...
          |--Takeout N
```
Here's the ls:
```
✓ /Volumes/SanDisk Extreme/Takeout % ls Takeout\ 1/Google\ Photos 
<OMITTED>/
<...>/
Archive/
<OMITTED>/
<...>/
Photos from 2015/
Photos from 2017/
<OMITTED>/
<...>/
print-subscriptions.json
shared_album_comments.json
```

Removed album names, for privacy. But all the photos have that general structure, with custom albums, and then the `Photos from YYYY` (inside the `./Photos from 2015/` folder from `Takeout 1` is all `.json` files, although I believe their corresponding image files might be in another `Takeout <N>/Photos from 2015/`folder, as I have several of those `Photos from 2015` with fragments of the (I'm assuming) complete folder, and the same goes for other years
```

**Comment by JoLander** [comment]
I just extractes all my takeout chunks into one folder.
As I said before, the specific album folders seems to contains copies of the files already present in the 'Photos from YYYY' folder.
It seems that they can safely get deleted to avoid duplicates (on the other hand it could be nice if the tool would also recreate the albums as folders. But this seems to be already in progress).
There are some special folders which do not contain duplicates within the 'Photos from YYYY' folder.
These are the 'Archive' and the 'Trash' folders. It seems that archived or deleted pictures are really 'moved' into the specific folders instead of being copied as in the albums.

**Comment by varnav** [comment]
Yup Google now names folders "Photos from YYYY". Tool says:

Wrong folder name: Photos:fro 12:00:00
You probably forgot to remove 'album folders' from your takeout folder

**Comment by fdterr** [comment]
> Yup Google now names folders "Photos from YYYY". Tool says:
> 
> Wrong folder name: Photos:fro 12:00:00
> You probably forgot to remove 'album folders' from your takeout folder

+1 also having this issue with that exact error

**Comment by cristian-milea** [comment]
Hi, does it work if I manually rename the folders from "Photos from 2016" to "2016-01-01" ?

**Comment by TheLastGimbus** [comment]
Huh... that's a very interesting question

Generally, this script uses folder name as a last chance when picture has no exif data nor .json was found. So if that happens, you will have photos with that date - you will have them listed in final stats file 👍

Tell me how it went if you do that

**Comment by mtthidoteu** [comment]
Hey guys! What is the status on this issue then? 
Cheers!

**Comment by TheLastGimbus** [comment]
Idk honestly - but it will probably quickly be solved - _**after**_ Christmas 🎄

**Comment by TheLastGimbus** [comment]
Hey @ everyone! Looks like @bitsondatadev almosted finished #36 - now, I need to test this before merging and making new version

Could you pull from his fork: https://github.com/bitsondatadev/GooglePhotosTakeoutHelper/tree/handle-albums-with-hash - and test if your "new takeouts" work with it? I would be really grateful!

**Comment by popy2k14** [comment]
Also looking forward for support of the new structure.
thx a lot.

**Comment by TheLastGimbus** [comment]
@popy2k14 if you are looking forward, help us in testing it 😉

Branch above *should* fully work now - just checkout and test if it works for you

**Comment by varnav** [comment]
I tested it under windows.
Worked for me. A lot of exif and json not found errors but I guess it's ok.

Correct "Created" date in windows is not set, please look at [my tool](https://github.com/varnav/ExifDate2FS) how I managed that.

**Comment by popy2k14** [comment]
Test under Windows 10 Pro 20H2 build with newest python 3.9.1 from MS store.
Sadly it does'nt work for me and quits with an exception:

`
D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash>python3 -m google_photos_takeout_helper -i D:\Temp\#google_fotos\Stefi -o D:\Temp\#google_fotos\Stefi_out --divide-to-dates
Heeeere we go!
=====================
Fixing files metadata and creation dates...
=====================
D:\Temp\#google_fotos\Stefi\Takeout\Google Fotos\Photos from 1990\11406828_10155658794900057_2219490452348186131_.jpg
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
No creation date found in exif!
Couldn't find json for file
Last chance, coping folder meta as date...
Couldn't pull datetime from album meta
ERROR! There was literally no option to set date!!!
TODO: We should do something about this - move it to some separate folder, or write it down in another .txt file...
D:\Temp\#google_fotos\Stefi\Takeout\Google Fotos\Photos from 2000\1.jpg
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
No creation date found in exif!
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Traceback (most recent call last):
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 352, in set_creation_date_from_str
    _windoza_setctime.setctime()
TypeError: setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 666, in <module>
    main()
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 587, in main
    for_all_files_recursive(
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 130, in for_all_files_recursive
    file_function(file)
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 523, in fix_metadata
    set_creation_date_from_str(file, date)
  File "D:\Temp\#google_fotos\GooglePhotosTakeoutHelper-handle-albums-with-hash\google_photos_takeout_helper\__main__.py", line 356, in set_creation_date_from_str
    raise ValueError(f"Error setting creation date from string: {str_datetime}")
ValueError: Error setting creation date from string: 2000:01:01 12:00:00
`

any hints?

thx

**Comment by TheLastGimbus** [comment]
> `python3 -m google_photos_takeout_helper`

You just used official version of script that is on pypi

To use our WIP code, you need to:
```bash
git clone https://github.com/bitsondatadev/GooglePhotosTakeoutHelper/ takeout-test
cd takeout-test
git checkout --track origin/handle-albums-with-hash
python3 google_photos_takeout_helper/__main__.py -i [INPUT] -o [OUTPUT]
```

**Comment by popy2k14** [comment]
I was using the new branch from the above link. Sadly, also with your approach, it doesnt work:

`
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. Alle Rechte vorbehalten.

D:\Temp\#google_fotos>git clone https://github.com/bitsondatadev/GooglePhotosTakeoutHelper/ takeout-test
Cloning into 'takeout-test'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 442 (delta 18), reused 30 (delta 10), pack-reused 396R
Receiving objects: 100% (442/442), 106.43 KiB | 864.00 KiB/s, done.
Resolving deltas: 100% (220/220), done.

D:\Temp\#google_fotos>cd takeout-test

D:\Temp\#google_fotos\takeout-test>git checkout --track origin/handle-albums-with-hash
Switched to a new branch 'handle-albums-with-hash'
Branch 'handle-albums-with-hash' set up to track remote branch 'handle-albums-with-hash' from 'origin'.

D:\Temp\#google_fotos\takeout-test>python3 google_photos_takeout_helper/__main__.py -i D:\Temp\#google_fotos\Stefi -o D:\Temp\#google_fotos\Stefi_out
Heeeere we go!
=====================
Fixing files metadata and creation dates...
=====================
D:\Temp\#google_fotos\Stefi\Takeout\Google Fotos\Photos from 1990\11406828_10155658794900057_2219490452348186131_.jpg
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
No creation date found in exif!
Couldn't find json for file
Last chance, coping folder meta as date...
Couldn't pull datetime from album meta
ERROR! There was literally no option to set date!!!
TODO: We should do something about this - move it to some separate folder, or write it down in another .txt file...
D:\Temp\#google_fotos\Stefi\Takeout\Google Fotos\Photos from 2000\1.jpg
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Wrong date format in exif!
2000:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'
No creation date found in exif!
Error setting creation date from string:
setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'
Traceback (most recent call last):
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 352, in set_creation_date_from_str
    _windoza_setctime.setctime()
TypeError: setctime() missing 2 required positional arguments: 'filepath' and 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 666, in <module>
    main()
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 587, in main
    for_all_files_recursive(
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 130, in for_all_files_recursive
    file_function(file)
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 523, in fix_metadata
    set_creation_date_from_str(file, date)
  File "D:\Temp\#google_fotos\takeout-test\google_photos_takeout_helper\__main__.py", line 356, in set_creation_date_from_str
    raise ValueError(f"Error setting creation date from string: {str_datetime}")
ValueError: Error setting creation date from string: 2000:01:01 12:00:00

D:\Temp\#google_fotos\takeout-test>
`

**Comment by TheLastGimbus** [comment]
> Wrong date format in exif!
1990:01:01 12:00:00
does not match '%Y:%m:%d %H:%M:%S'

How the hell does `1990:01:01 12:00:00` not match Y-M-D H-M-S??

# :shrug:

**Comment by popy2k14** [comment]
Thats the question :-)

**Comment by popy2k14** [comment]
I have found the issue.
Change line 352 from:

`                _windoza_setctime.setctime()`

to

`                _windoza_setctime.setctime(file, timestamp)`

And it works.

Seems there was the two arguments file & timestamp missing for the "setctime" function.
This was throwing the exception JUST on windows maschines.

**Comment by TheLastGimbus** [comment]
Oh, I had to be really asleep when I was writing this xD

[fixed](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/pull/36/commits/0b9e9b94cb876dad2df87452d9746c5ae1f2c421), now try it

**Comment by popy2k14** [comment]
Its running now, but i got very often the message that no json was found.

Output of script:

`
D:\Temp\#google_fotos\Stefi\Takeout\Google Fotos\Photos from 2018\DSC05418(1).jpg
Couldn't find json for file
`

After a look at the files if found this:

![image](https://user-images.githubusercontent.com/6324597/104123164-c18ea080-5349-11eb-8b4c-50be5f327103.png)

There is an (1) at another position in the filename.
It seems the json is the correct one.

Will this not be taken into account?

**Comment by popy2k14** [comment]
To overcome this i have done the following workaround on my folder with WSL:

`find . -depth -exec rename 's/\(1\)//g' {} +`

This removes the (1) and running the script afterwards sets the exif data from json correctly.

Would be nice if this would be confirmed and integrated into the script.

**Comment by TheLastGimbus** [comment]
It's okay, we have plans for better "json finding" - most important - does it generally work?

**Comment by popy2k14** [comment]
Yeah I think it's necessary to a better way to find the json file.

Generally: it works now.

**Comment by TheLastGimbus** [comment]
# :tada:

Will push new version to PyPi very soon
